/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import Model.InventoryModel;
import Model.item;
import Model.SaleModel;
import Model.Sale;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import Controller.AdminController;
import java.awt.Color;
import java.util.ArrayList;
import java.time.LocalDate;
import java.util.HashMap;





/**
 *
 * @author dell
 */
public class AdminView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminView.class.getName());
     private JTable lowStockTable;
     private boolean lowStockAlertShown = false;
     
  private InventoryModel inventoryModel;
  private JTable recentSalesTable;
private SaleModel saleModel;
private AdminController adminController; 
private JTable inventoryTable;



    /**
     * Creates new form AdminView
     */
    public AdminView(InventoryModel inventoryModel, SaleModel saleModel) {
        initComponents();
        setupInventoryTable();
          this.inventoryModel =  inventoryModel;
           inventoryModel.addItem(new item("P001", "Paracetamol",  5, 4, 40.00));
           
           this.saleModel =  saleModel;
          saleModel.addSale(new Sale("P001", "Paracetamol", 2, 20.0, "user1", LocalDateTime.now()));
               adminController = new AdminController(inventoryModel, saleModel, this);
          setupLowStockTable();
          loadLowStockData();
          setupRecentSalesTable();
          loadRecentSalesData();
          loadSalesReportTable();
          updateSummary() ;
          refreshInventoryTable();
          lowStock();
          //showLowStock();
          javax.swing.SwingUtilities.invokeLater(() -> {
        showLowStock();
    });
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminSort = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();
        InventoryPanel = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        adminCombo = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        inventoryButtonPanel = new javax.swing.JPanel();
        addItemButton = new javax.swing.JButton();
        updateStockButton = new javax.swing.JButton();
        deleteItemButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        inventoryTablePanel = new javax.swing.JPanel();
        SalePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salesTitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salesTablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salesControlPanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        salesSortCombo = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        fromDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        toDateField = new javax.swing.JTextField();
        Analytics = new javax.swing.JPanel();
        SummaryPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTotalProducts = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTotalSale = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelLowStock = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTopProduct = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        analyticsTablePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Dashboard = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        dashboardCenteralPanel = new javax.swing.JPanel();
        lowStockPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recentSalesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        totalProductsLabel = new javax.swing.JLabel();
        lowStockLabel = new javax.swing.JLabel();
        totalSalesLabel = new javax.swing.JLabel();

        adminSort.setText("Sort");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Inventory System Admin Panel");

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(44, 62, 80));
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(44, 62, 80));
        jButton2.setText("Inventory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 62, 80));
        jButton3.setText("Sales");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(44, 62, 80));
        jButton4.setText("Analytics");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ContentPanel.setLayout(new java.awt.CardLayout());

        InventoryPanel.setLayout(new java.awt.BorderLayout());

        title.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Inventory Management");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        title.add(jLabel7);

        jLabel15.setPreferredSize(new java.awt.Dimension(200, 10));
        title.add(jLabel15);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Sort By");
        title.add(jLabel13);

        adminCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price (Ascending)", " ", "Price (Descending)", " ", "Quantity (Ascending)", " ", "Quantity (Descending)", " ", "Name (A-Z)", " ", "Name (Z-A)" }));
        adminCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminComboActionPerformed(evt);
            }
        });
        title.add(adminCombo);

        jButton8.setText("Sort");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        title.add(jButton8);

        InventoryPanel.add(title, java.awt.BorderLayout.NORTH);

        addItemButton.setText("Add");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(addItemButton);

        updateStockButton.setText("Update");
        updateStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(updateStockButton);

        deleteItemButton.setText("Delete");
        deleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(deleteItemButton);

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(undoButton);

        InventoryPanel.add(inventoryButtonPanel, java.awt.BorderLayout.SOUTH);

        inventoryTablePanel.setLayout(new java.awt.BorderLayout());
        InventoryPanel.add(inventoryTablePanel, java.awt.BorderLayout.CENTER);

        ContentPanel.add(InventoryPanel, "inventory");

        SalePanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Sale");
        SalePanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Sales Report");
        salesTitlePanel.add(jLabel1);

        SalePanel.add(salesTitlePanel, java.awt.BorderLayout.PAGE_START);

        salesTablePanel.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sale Id", "Product Name", "Quantity", "Price", "User", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        salesTablePanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        salesControlPanel.add(jButton5);

        jButton6.setText("Sort");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        salesControlPanel.add(jButton6);

        salesSortCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "Quantity", " " }));
        salesSortCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesSortComboActionPerformed(evt);
            }
        });
        salesControlPanel.add(salesSortCombo);

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        salesControlPanel.add(jButton7);

        jLabel8.setText("From Date");
        jPanel2.add(jLabel8);

        jButton10.setText("Undo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        fromDate.setColumns(15);
        jPanel2.add(fromDate);

        jLabel9.setText("To Date");
        jPanel2.add(jLabel9);

        toDateField.setColumns(15);
        jPanel2.add(toDateField);

        salesControlPanel.add(jPanel2);

        salesTablePanel.add(salesControlPanel, java.awt.BorderLayout.PAGE_END);

        SalePanel.add(salesTablePanel, java.awt.BorderLayout.CENTER);

        ContentPanel.add(SalePanel, "sale");

        Analytics.setLayout(new java.awt.BorderLayout());

        SummaryPanel.setLayout(new java.awt.GridLayout(2, 2, 30, 30));

        jLabelTotalProducts.setText("Total Products");
        jPanel3.add(jLabelTotalProducts);

        jLabel14.setText("0");
        jPanel3.add(jLabel14);

        SummaryPanel.add(jPanel3);

        jLabelTotalSale.setText("Total Sales");
        jPanel4.add(jLabelTotalSale);

        jLabel10.setText("0");
        jPanel4.add(jLabel10);

        SummaryPanel.add(jPanel4);

        jLabelLowStock.setText("Low Stock");
        jPanel5.add(jLabelLowStock);

        jLabel11.setText("0");
        jPanel5.add(jLabel11);

        SummaryPanel.add(jPanel5);

        jTopProduct.setText("Top Products");
        jPanel6.add(jTopProduct);

        jLabel12.setText("0");
        jPanel6.add(jLabel12);

        SummaryPanel.add(jPanel6);

        Analytics.add(SummaryPanel, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Analytics");
        Title.add(jLabel3);

        Analytics.add(Title, java.awt.BorderLayout.NORTH);

        analyticsTablePanel.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Total Sale", "Total Revenue"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        analyticsTablePanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        Analytics.add(analyticsTablePanel, java.awt.BorderLayout.SOUTH);

        ContentPanel.add(Analytics, "analytics");

        Dashboard.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Admin Dashboard");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        titlePanel.add(jLabel5);

        jLabel16.setPreferredSize(new java.awt.Dimension(800, 10));
        titlePanel.add(jLabel16);

        jButton9.setText("Log Out");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        titlePanel.add(jButton9);

        Dashboard.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        dashboardCenteralPanel.setLayout(new java.awt.GridLayout(1, 2));

        lowStockPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 76, 60));
        jLabel4.setText("Low Stock Alert");
        lowStockPanel.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(236, 240, 241));
        lowStockPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        dashboardCenteralPanel.add(lowStockPanel);

        recentSalesPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 174, 96));
        jLabel6.setText("                   Recent Sales");
        recentSalesPanel.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        dashboardCenteralPanel.add(recentSalesPanel);

        Dashboard.add(dashboardCenteralPanel, java.awt.BorderLayout.CENTER);

        summaryPanel.setBackground(new java.awt.Color(245, 247, 250));
        summaryPanel.setLayout(new java.awt.GridLayout(1, 3));

        totalProductsLabel.setBackground(new java.awt.Color(52, 152, 219));
        totalProductsLabel.setText("Total Products");
        summaryPanel.add(totalProductsLabel);
        summaryPanel.add(lowStockLabel);

        totalSalesLabel.setText("jLabel9");
        summaryPanel.add(totalSalesLabel);

        Dashboard.add(summaryPanel, java.awt.BorderLayout.PAGE_END);

        ContentPanel.add(Dashboard, "dashboard");

        getContentPane().add(ContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
    cl.show(ContentPanel, "analytics");
     adminController.loadAnalytics();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
cl.show(ContentPanel, "inventory");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
        cl.show( ContentPanel, "dashboard");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout) ContentPanel.getLayout();
    cl.show(ContentPanel, "sale");
    loadSalesReportTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemButtonActionPerformed
        // TODO add your handling code here:
        adminController.deleteProduct();
        /* int row = inventoryTable.getSelectedRow();
         if (row == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a product to delete!",
            "No Selection",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
          String productId = inventoryTable.getValueAt(row, 0).toString();
           int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete Product ID: " + productId + "?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );
           if (confirm != JOptionPane.YES_OPTION) {
        return; 
    }
           boolean deleted = inventoryModel.deleteItem(productId);

    if (deleted) {
        loadInventoryTable();
        loadLowStockData();
       updateSummary();
        JOptionPane.showMessageDialog(this, "Item deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(
            this,
            "Delete failed!",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }*/

    }//GEN-LAST:event_deleteItemButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
        adminController.undoInventory();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
         adminController.addProduct();
       
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void updateStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockButtonActionPerformed
        // TODO add your handling code here:
        adminController.updateProduct();
       
    }//GEN-LAST:event_updateStockButtonActionPerformed

    private void adminComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminComboActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        loadSalesReportTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void salesSortComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesSortComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesSortComboActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        adminController.sortProducts();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        /* saleModel.clearSales();          // clear using stack
    loadSalesReportTable();          // refresh table
    updateSummary();                 // update counts
    JOptionPane.showMessageDialog(this, "Sales Cleared!");*/
        boolean cleared = saleModel.clearSales();

    if (cleared) {
        loadSalesReportTable();
        loadRecentSalesData();
        updateSummary();
        JOptionPane.showMessageDialog(this, "Sales Cleared!");
    } else {
        JOptionPane.showMessageDialog(this, "Sales list already empty!");
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        adminController.logout();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
       boolean restored = saleModel.undoClearSales();

    if (restored) {
        loadSalesReportTable();
        loadRecentSalesData();
        updateSummary();
        JOptionPane.showMessageDialog(this, "Undo Successful!");
    } else {
        JOptionPane.showMessageDialog(this, "Nothing to Undo!");
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
        LocalDate from = LocalDate.parse(this.fromDate.getText().trim());
        LocalDate to   = LocalDate.parse(toDateField.getText().trim());

        String option = salesSortCombo.getSelectedItem().toString();

        if (option.equalsIgnoreCase("Quantity")) {
            adminController.showSalesByQuantity(from, to);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid date format! Use yyyy-MM-dd");
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    
   /*public void setupLowStockTable() {

    String[] columns = { "Product Name", "Quantity", "Minimum" };

    DefaultTableModel model = new DefaultTableModel(columns, 0);
    lowStockTable = new JTable(model);

    JScrollPane scrollPane = new JScrollPane(lowStockTable);

    lowStockPanel.add(scrollPane, BorderLayout.CENTER);
}*/
    public void setupLowStockTable() {
    String[] columns = { "Product Name", "Quantity", "Minimum" };
    DefaultTableModel model = new DefaultTableModel(columns, 0);
    lowStockTable = new JTable(model);

    jScrollPane1.setViewportView(lowStockTable); // correct
}

    public void loadLowStockData() {

    DefaultTableModel model = (DefaultTableModel) lowStockTable.getModel();
    model.setRowCount(0);

    for (item i : inventoryModel.getLowStockItem()) {
        model.addRow(new Object[]{
            i.getName(),
            i.getQuantity(),
            i.getMinimum()
        });
    }
}
    public void setupRecentSalesTable() {

    String[] columns = { "User", "Product", "Qty", "Price", "Date" };

    DefaultTableModel model = new DefaultTableModel(columns, 0);
    recentSalesTable = new JTable(model);

    JScrollPane scrollPane = new JScrollPane(recentSalesTable);
    recentSalesPanel.add(scrollPane, BorderLayout.CENTER);
}
    /*public void loadRecentSalesData() {

    DefaultTableModel model = (DefaultTableModel) recentSalesTable.getModel();
    model.setRowCount(0);

    for (Sale s : saleModel.getAllSaleItems()) {
        model.addRow(new Object[]{
            s.getUsername(),
            s.getName(),
            s.getQuantity(),
            s.getPrice(),
            s.getDate()
        });
    }
}*/
    public void loadRecentSalesData() {

    DefaultTableModel model = (DefaultTableModel) recentSalesTable.getModel();
    model.setRowCount(0);

    for (Sale s : saleModel.getRecentSalesQueue()) {
        model.addRow(new Object[]{
            s.getUsername(),
            s.getName(),
            s.getQuantity(),
            s.getPrice(),
            s.getDate()
        });
    }
}

    
    public void updateSummary() {

    totalProductsLabel.setText(
        "Total Products: " + inventoryModel.getAllItems().size()
    );

    lowStockLabel.setText(
        "Low Stock Items: " + inventoryModel.getLowStockItem().size()
    );

    totalSalesLabel.setText(
        "Total Sales: " + saleModel.getAllSaleItems().size()
    );
}
   
    public void setupInventoryTable() {

    String[] columns = {
        "Product ID", "Name", "Quantity", "Minimum", "Price"
    };

    DefaultTableModel model = new DefaultTableModel(columns, 0);
    inventoryTable = new JTable(model);

    JScrollPane scrollPane = new JScrollPane(inventoryTable);
    inventoryTablePanel.add(scrollPane, BorderLayout.CENTER);
}
    public void refreshInventoryTable() {

    DefaultTableModel model =
        (DefaultTableModel) inventoryTable.getModel();

    model.setRowCount(0); // clear table

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[] {
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
    }
}
    public void loadInventoryTable() {
    DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
    model.setRowCount(0); // clear table

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[]{
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
    }
}
    public JTable getInvetoryTable()
    {
        return inventoryTable;
    }
    public void loadSalesTable(ArrayList<Sale> sales) {

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    int saleId = 1;
    for (Sale s : sales) {
        model.addRow(new Object[]{
            saleId++,
            s.getName(),
            s.getQuantity(),
            s.getPrice(),
            s.getUsername(),
            s.getDate()
        });
    }
}

    public void loadSalesReportTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    int saleId = 1;

    for (Sale s : saleModel.getAllSaleItems()) {
        model.addRow(new Object[]{
            saleId++,          // Sale Id
            s.getName(),       // Product Name
            s.getQuantity(),   // Quantity
            s.getPrice(),      // Price
            s.getUsername(),   // User
            s.getDate()        // Date
        });
    }
}
    public static void selectionSortByProductName(java.util.LinkedList<Sale> list) {

    int size = list.size();

    for (int step = 0; step < size - 1; step++) {

        int minIdx = step;

        for (int i = step + 1; i < size; i++) {

            if (list.get(i).getName()
                    .compareToIgnoreCase(list.get(minIdx).getName()) < 0) {

                minIdx = i;
            }
        }

        // swap
        if (minIdx != step) {
            Sale temp = list.get(step);
            list.set(step, list.get(minIdx));
            list.set(minIdx, temp);
        }
    }
}
public static void bubbleSortByQuantity(java.util.LinkedList<Sale> list) {

    int n = list.size();
    boolean swapped;

    for (int i = 0; i < n - 1; i++) {
        swapped = false;

        for (int j = 0; j < n - i - 1; j++) {

            if (list.get(j).getQuantity() > list.get(j + 1).getQuantity()) {

                Sale temp = list.get(j);
                list.set(j, list.get(j + 1));
                list.set(j + 1, temp);

                swapped = true;
            }
        }

        if (!swapped) {
            break; // already sorted
        }
    }
}
    public void setTopProductValue(String text) {
    jLabel12.setText(text);
    }
    public void setTotalProductsValue(String text) {
    jLabel14.setText(text);
}

public void setTotalSalesValue(String text) {
    jLabel10.setText(text);
}

public void setLowStockValue(String text) {
    jLabel11.setText(text);
}
public JTable getAnalyticsTable() {
    return jTable2;
}
public String getSelectedSortOption() {
    return adminCombo.getSelectedItem().toString();
}



  // sorting
public  ArrayList<item> mergeSortByPriceAscending(ArrayList<item> list) {

    if (list.size() <= 1) {
        return list;
    }

    int mid = list.size() / 2;

    ArrayList<item> left = new java.util.ArrayList<>(list.subList(0, mid));
    ArrayList<item> right = new java.util.ArrayList<>(list.subList(mid, list.size()));

    left = mergeSortByPriceAscending(left);
    right = mergeSortByPriceAscending(right);

    return mergeByPriceAscending(left, right);
}

public ArrayList<item> mergeByPriceAscending(ArrayList<item> left,
                                                        ArrayList<item> right) {

    ArrayList<item> result = new ArrayList<>();

    while (!left.isEmpty() && !right.isEmpty()) {

        double leftPrice = left.get(0).getPrice();
        double rightPrice = right.get(0).getPrice();

        // ASCENDING
        if (leftPrice <= rightPrice) {
            result.add(left.remove(0));
        } else {
            result.add(right.remove(0));
        }
    }

    result.addAll(left);
    result.addAll(right);

    return result;
}

// merge sort by descending price
public ArrayList<item> mergeSortByPriceDescending(ArrayList<item> list) {

    if (list.size() <= 1) {
        return list;
    }

    int mid = list.size() / 2;

    ArrayList<item> left = new ArrayList<>(list.subList(0, mid));
    ArrayList<item> right = new ArrayList<>(list.subList(mid, list.size()));

    left = mergeSortByPriceDescending(left);
    right = mergeSortByPriceDescending(right);

    return mergeByPriceDescending(left, right);
}

public ArrayList<item> mergeByPriceDescending(ArrayList<item> left,
                                                         ArrayList<item> right) {

    ArrayList<item> result = new java.util.ArrayList<>();

    while (!left.isEmpty() && !right.isEmpty()) {

        double leftPrice = left.get(0).getPrice();
        double rightPrice = right.get(0).getPrice();

        //  DESCENDING
        if (leftPrice >= rightPrice) {
            result.add(left.remove(0));
        } else {
            result.add(right.remove(0));
        }
    }

    result.addAll(left);
    result.addAll(right);

    return result;
}
// asscending  insertion by quantity
public void insertionSortByQuantityAscending(java.util.ArrayList<item> list) {

    int size = list.size();

    for (int step = 1; step < size; step++) {

        item key = list.get(step);
        int keyQty = key.getQuantity();
        int j = step - 1;

        while (j >= 0 && keyQty < list.get(j).getQuantity()) {
            list.set(j + 1, list.get(j));
            j--;
        }

        list.set(j + 1, key);
    }
}

// insertion quantity for descending
public static void insertionSortByQuantityDescending(java.util.ArrayList<item> list) {

    int size = list.size();

    for (int step = 1; step < size; step++) {

        item key = list.get(step);
        int keyQty = key.getQuantity();
        int j = step - 1;

       // DESCENDING: bigger quantity first
        while (j >= 0 && keyQty > list.get(j).getQuantity()) {
            list.set(j + 1, list.get(j));
            j--;
        }

        list.set(j + 1, key);
    }
}



public void loadSortedProductData(ArrayList<item> sortedList) {

    DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
    model.setRowCount(0); // clear table

    for (item i : sortedList) {
        model.addRow(new Object[]{
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
    }
}


// alert 
public void lowStock()
    {
       inventoryTable.setSelectionBackground(Color.PINK);
       inventoryTable.setSelectionForeground(Color.BLACK);
       inventoryTable.clearSelection();
       for (int row = 0; row<inventoryTable.getRowCount(); row++)
       {
           int quantity = Integer.parseInt(inventoryTable.getValueAt(row, 2).toString());
           int minimum = Integer.parseInt(inventoryTable.getValueAt(row, 3).toString());
           
           if (quantity<= minimum)
           {
               inventoryTable.addRowSelectionInterval(row , row);
           }
                  
           
       }
       
       
        
       
    }
    private void showLowStock()
    {
        if(lowStockAlertShown)
        {
            return ; // alerady shown 
        }
        boolean hasLowStock = false;
        for(item i: inventoryModel.getAllItems())
        {
            if(i.getQuantity()<=i.getMinimum())
            {
                hasLowStock = true;
                break;
            }
        }
        if(hasLowStock)
        {
            java.awt.Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Some products are running low on stock!",
                    "Low Stock alert",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                 );
            lowStockAlertShown = true;
            
        }
    }
    public void loadUserQuantityTable(HashMap<String, Integer> userTotals) {

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    // change column names for this view
    model.setColumnIdentifiers(new String[]{"User", "Total Quantity"});

    for (String user : userTotals.keySet()) {
        model.addRow(new Object[]{user, userTotals.get(user)});
    }
}
    public void loadQuantityTable(ArrayList<Sale> sales) {

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    // reset original columns
    model.setColumnIdentifiers(new String[]{
        "Sale Id", "Product Name", "Quantity", "Price", "User", "Date"
    });

    int saleId = 1;
    for (Sale s : sales) {
        model.addRow(new Object[]{
            saleId++,
            s.getName(),
            s.getQuantity(),
            s.getPrice(),
            s.getUsername(),
            s.getDate()
        });
    }
}


    









   

// upto here
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         InventoryModel inventoryModel = new InventoryModel();
SaleModel saleModel = new SaleModel();
java.awt.EventQueue.invokeLater(() ->{
    //new AdminView(inventoryModel, saleModel).setVisible(true)
        AdminView view = new AdminView(inventoryModel, saleModel);
    view.setVisible(true);
    //view.showLowStock(); 
            });


//java.awt.EventQueue.invokeLater(() -> new UserView(inventoryModel, saleModel).setVisible(true));

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(() -> new AdminView().setVisible(true));
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Analytics;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel InventoryPanel;
    private javax.swing.JPanel SalePanel;
    private javax.swing.JPanel SummaryPanel;
    private javax.swing.JPanel Title;
    private javax.swing.JButton addItemButton;
    private javax.swing.JComboBox<String> adminCombo;
    private javax.swing.JButton adminSort;
    private javax.swing.JPanel analyticsTablePanel;
    private javax.swing.JPanel dashboardCenteralPanel;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JTextField fromDate;
    private javax.swing.JPanel inventoryButtonPanel;
    private javax.swing.JPanel inventoryTablePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLowStock;
    private javax.swing.JLabel jLabelTotalProducts;
    private javax.swing.JLabel jLabelTotalSale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jTopProduct;
    private javax.swing.JLabel lowStockLabel;
    private javax.swing.JPanel lowStockPanel;
    private javax.swing.JPanel recentSalesPanel;
    private javax.swing.JPanel salesControlPanel;
    private javax.swing.JComboBox<String> salesSortCombo;
    private javax.swing.JPanel salesTablePanel;
    private javax.swing.JPanel salesTitlePanel;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JPanel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField toDateField;
    private javax.swing.JLabel totalProductsLabel;
    private javax.swing.JLabel totalSalesLabel;
    private javax.swing.JButton undoButton;
    private javax.swing.JButton updateStockButton;
    // End of variables declaration//GEN-END:variables
}
