/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import Model.InventoryModel;
import Model.item;
import Model.SaleModel;
import Model.Sale;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;



/**
 *
 * @author dell
 */
public class AdminView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminView.class.getName());
     private JTable lowStockTable;
  private InventoryModel inventoryModel;
  private JTable recentSalesTable;
private SaleModel saleModel;
private JTable inventoryTable;



    /**
     * Creates new form AdminView
     */
    public AdminView(InventoryModel inventoryModel, SaleModel saleModel) {
        initComponents();
        setupInventoryTable();
          this.inventoryModel =  inventoryModel;
            inventoryModel.addItem(new item("P001", "Paracetamol",  10, 3, 20.00));
           this.saleModel =  saleModel;
           saleModel.addSale(new Sale("P001", "Paracetamol", 2, 20.0, "user1", LocalDateTime.now()));

          setupLowStockTable();
          loadLowStockData();
          setupRecentSalesTable();
          loadRecentSalesData();
          updateSummary() ;
          refreshInventoryTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();
        InventoryPanel = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        inventoryButtonPanel = new javax.swing.JPanel();
        addItemButton = new javax.swing.JButton();
        updateStockButton = new javax.swing.JButton();
        deleteItemButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        inventoryTablePanel = new javax.swing.JPanel();
        SalePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Analytics = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dashboardCenteralPanel = new javax.swing.JPanel();
        lowStockPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recentSalesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        totalProductsLabel = new javax.swing.JLabel();
        lowStockLabel = new javax.swing.JLabel();
        totalSalesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Inventory System Admin Panel");

        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Inventory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Sales");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Analytics");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ContentPanel.setLayout(new java.awt.CardLayout());

        InventoryPanel.setLayout(new java.awt.BorderLayout());

        title.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Inventory Management");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        title.add(jLabel7);

        InventoryPanel.add(title, java.awt.BorderLayout.NORTH);

        addItemButton.setText("Add");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(addItemButton);

        updateStockButton.setText("Update");
        updateStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(updateStockButton);

        deleteItemButton.setText("Delete");
        deleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(deleteItemButton);

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        inventoryButtonPanel.add(undoButton);

        InventoryPanel.add(inventoryButtonPanel, java.awt.BorderLayout.SOUTH);

        inventoryTablePanel.setLayout(new java.awt.BorderLayout());
        InventoryPanel.add(inventoryTablePanel, java.awt.BorderLayout.CENTER);

        ContentPanel.add(InventoryPanel, "inventory");

        SalePanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Sale");
        SalePanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        ContentPanel.add(SalePanel, "sale");

        Analytics.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Sale");
        Analytics.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        ContentPanel.add(Analytics, "analytics");

        Dashboard.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Admin Dashboard");
        titlePanel.add(jLabel5);

        Dashboard.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        dashboardCenteralPanel.setLayout(new java.awt.GridLayout(1, 2));

        lowStockPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Low Stock Alert");
        lowStockPanel.add(jLabel4, java.awt.BorderLayout.PAGE_START);
        lowStockPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        dashboardCenteralPanel.add(lowStockPanel);

        recentSalesPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Recent Sales");
        recentSalesPanel.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        dashboardCenteralPanel.add(recentSalesPanel);

        Dashboard.add(dashboardCenteralPanel, java.awt.BorderLayout.CENTER);

        summaryPanel.setLayout(new java.awt.GridLayout(1, 3));
        summaryPanel.add(totalProductsLabel);
        summaryPanel.add(lowStockLabel);

        totalSalesLabel.setText("jLabel9");
        summaryPanel.add(totalSalesLabel);

        Dashboard.add(summaryPanel, java.awt.BorderLayout.PAGE_END);

        ContentPanel.add(Dashboard, "dashboard");

        getContentPane().add(ContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
    cl.show(ContentPanel, "analytics");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
cl.show(ContentPanel, "inventory");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
        cl.show( ContentPanel, "dashboard");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout) ContentPanel.getLayout();
    cl.show(ContentPanel, "sale");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemButtonActionPerformed
        // TODO add your handling code here:
         int row = inventoryTable.getSelectedRow();
         if (row == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a product to delete!",
            "No Selection",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
          String productId = inventoryTable.getValueAt(row, 0).toString();
           int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete Product ID: " + productId + "?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );
           if (confirm != JOptionPane.YES_OPTION) {
        return; 
    }
           boolean deleted = inventoryModel.deleteItem(productId);

    if (deleted) {
        loadInventoryTable();
        loadLowStockData();
       updateSummary();
        JOptionPane.showMessageDialog(this, "Item deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(
            this,
            "Delete failed!",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_deleteItemButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undoButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
         
        try {
        String id = JOptionPane.showInputDialog(this, "Enter Product ID:");

        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Product ID cannot be empty!");
            return;
        }

        id = id.trim().toUpperCase(); // ⭐ CASE INSENSITIVE

        if (!id.matches("^[A-Z][A-Z0-9]*$")) {
            JOptionPane.showMessageDialog(
                this,
                "Invalid Product ID!\nIt must start with a letter.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        String name = JOptionPane.showInputDialog(this, "Enter Product Name:");

if (name == null || name.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Product name cannot be empty!");
    return;
}

if (!name.matches("^[A-Za-z ]+[0-9]*$")) {
    JOptionPane.showMessageDialog(
        this,
        "Invalid Product Name!",
        "Invalid Input",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}

        int quantity;
        try
        {
            quantity = Integer.parseInt(
            JOptionPane.showInputDialog(this, "Enter Quantity:")
        );
                if (quantity <= 0) {
        JOptionPane.showMessageDialog(
            this,
            "Price must be greater than 0!",
            "Invalid Input",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }
        }
        catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(
        this,
        "Invalid Price!\nPlease enter a numeric value.",
        "Invalid Input",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}
       
        int minimum = Integer.parseInt(
            JOptionPane.showInputDialog(this, "Enter Minimum Stock:")
        );
        double price;
        try{
             price= Double.parseDouble(
            JOptionPane.showInputDialog(this, "Enter Price:")
        );
              if (price <= 0) {
        JOptionPane.showMessageDialog(
            this,
            "Price must be greater than 0!",
            "Invalid Input",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }
             
        }catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(
        this,
        "Invalid Price!\nPlease enter a numeric value.",
        "Invalid Input",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}
        

        if ( minimum < 0 ) {
            JOptionPane.showMessageDialog(
                this,
                " Minimum  must be positive!",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        item newItem = new item(id, name, quantity, minimum, price);

        boolean added = inventoryModel.addItem(newItem);

        if (added) {
            refreshInventoryTable();
            loadLowStockData();   
             updateSummary(); 
             
            JOptionPane.showMessageDialog(this, "Item added successfully!");
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Product ID already exists!",
                "Duplicate Error",
                JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter valid numeric values!",
            "Invalid Input",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void updateStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockButtonActionPerformed
        // TODO add your handling code here:
        
        int row = inventoryTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
            "Select a product to update!",
            "No Selection",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    String productId = inventoryTable.getValueAt(row, 0).toString();

    try {
        int quantity = Integer.parseInt(
            JOptionPane.showInputDialog(this, "Enter New Quantity:")
        );

        int minimum = Integer.parseInt(
            JOptionPane.showInputDialog(this, "Enter New Minimum Stock:")
        );

        double price = Double.parseDouble(
            JOptionPane.showInputDialog(this, "Enter New Price:")
        );

        if (quantity < 0 || minimum < 0 || price <= 0) {
            JOptionPane.showMessageDialog(this, "Invalid values entered!");
            return;
        }

        inventoryModel.updateItem(productId, quantity, minimum, price);
        refreshInventoryTable();
        loadLowStockData();
        updateSummary();

        JOptionPane.showMessageDialog(this, "Item updated successfully!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Please enter valid numeric values!",
            "Invalid Input",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateStockButtonActionPerformed

    
    private void setupLowStockTable() {

    String[] columns = { "Product Name", "Quantity", "Minimum" };

    DefaultTableModel model = new DefaultTableModel(columns, 0);
    lowStockTable = new JTable(model);

    JScrollPane scrollPane = new JScrollPane(lowStockTable);

    lowStockPanel.add(scrollPane, BorderLayout.CENTER);
}
    private void loadLowStockData() {

    DefaultTableModel model = (DefaultTableModel) lowStockTable.getModel();
    model.setRowCount(0);

    for (item i : inventoryModel.getLowStockItem()) {
        model.addRow(new Object[]{
            i.getName(),
            i.getQuantity(),
            i.getMinimum()
        });
    }
}
    private void setupRecentSalesTable() {

    String[] columns = { "User", "Product", "Qty", "Price", "Date" };

    DefaultTableModel model = new DefaultTableModel(columns, 0);
    recentSalesTable = new JTable(model);

    JScrollPane scrollPane = new JScrollPane(recentSalesTable);
    recentSalesPanel.add(scrollPane, BorderLayout.CENTER);
}
    private void loadRecentSalesData() {

    DefaultTableModel model = (DefaultTableModel) recentSalesTable.getModel();
    model.setRowCount(0);

    for (Sale s : saleModel.getAllSaleItems()) {
        model.addRow(new Object[]{
            s.getUsername(),
            s.getName(),
            s.getQuantity(),
            s.getPrice(),
            s.getDate()
        });
    }
}
    
    private void updateSummary() {

    totalProductsLabel.setText(
        "Total Products: " + inventoryModel.getAllItems().size()
    );

    lowStockLabel.setText(
        "Low Stock Items: " + inventoryModel.getLowStockItem().size()
    );

    totalSalesLabel.setText(
        "Total Sales: " + saleModel.getAllSaleItems().size()
    );
}
   
    private void setupInventoryTable() {

    String[] columns = {
        "Product ID", "Name", "Quantity", "Minimum", "Price"
    };

    DefaultTableModel model = new DefaultTableModel(columns, 0);
    inventoryTable = new JTable(model);

    JScrollPane scrollPane = new JScrollPane(inventoryTable);
    inventoryTablePanel.add(scrollPane, BorderLayout.CENTER);
}
    private void refreshInventoryTable() {

    DefaultTableModel model =
        (DefaultTableModel) inventoryTable.getModel();

    model.setRowCount(0); // clear table

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[] {
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
    }
}
    private void loadInventoryTable() {
    DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
    model.setRowCount(0); // clear table

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[]{
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
    }
}








   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         InventoryModel inventoryModel = new InventoryModel();
SaleModel saleModel = new SaleModel();
java.awt.EventQueue.invokeLater(() ->
    new AdminView(inventoryModel, saleModel).setVisible(true)
);

//java.awt.EventQueue.invokeLater(() -> new UserView(inventoryModel, saleModel).setVisible(true));

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(() -> new AdminView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Analytics;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel InventoryPanel;
    private javax.swing.JPanel SalePanel;
    private javax.swing.JButton addItemButton;
    private javax.swing.JPanel dashboardCenteralPanel;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JPanel inventoryButtonPanel;
    private javax.swing.JPanel inventoryTablePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lowStockLabel;
    private javax.swing.JPanel lowStockPanel;
    private javax.swing.JPanel recentSalesPanel;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JPanel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel totalProductsLabel;
    private javax.swing.JLabel totalSalesLabel;
    private javax.swing.JButton undoButton;
    private javax.swing.JButton updateStockButton;
    // End of variables declaration//GEN-END:variables
}
