/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.SaleModel;

/**
 *
 * @author dell
 */
public class PurchaseView extends javax.swing.JFrame {
    private SaleModel saleModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PurchaseView.class.getName());

    /**
     * Creates new form PurchaseView
     */
    public PurchaseView(SaleModel saleModel) {
        initComponents();
        this.saleModel = saleModel;
        setSize(800,450);
        setLocationRelativeTo(null);
    }
    public javax.swing.JTable getTable() {
    return purchaseTable;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseTable = new javax.swing.JTable();
        ActionPanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("My Purchase History");
        setResizable(false);

        jLabel1.setText("Purchase Histroy");
        titlePanel.add(jLabel1);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        TablePanel.setLayout(new java.awt.BorderLayout());

        purchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sale Id", "Product Name", "Quantity", "Price", "Date"
            }
        ));
        purchaseTable.setRowHeight(25);
        jScrollPane1.setViewportView(purchaseTable);

        TablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        ActionPanel.add(btnClose);

        TablePanel.add(ActionPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(TablePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
SaleModel saleModel = new SaleModel();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PurchaseView(saleModel).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionPanel;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable purchaseTable;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
