/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.table.DefaultTableModel;
import Model.InventoryModel;
import Model.item;
import Model.SaleModel;

/**
 *
 * @author dell
 */
public class UserView extends javax.swing.JFrame {
    private InventoryModel inventoryModel;
    private SaleModel saleModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserView.class.getName());

    /**
     * Creates new form UserView
     */
    public UserView(InventoryModel inventoryModel , SaleModel saleModel) {
       this.inventoryModel = inventoryModel;
       this.saleModel =  saleModel;
        initComponents();
         //this.inventoryModel = inventoryModel;
         setupProductTable();
         loadProductData();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProductTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productName = new javax.swing.JTable();
        BuyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User View");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("User Dashboard - Smart Inventory System");
        TitlePanel.add(jLabel1);

        getContentPane().add(TitlePanel, java.awt.BorderLayout.PAGE_START);

        ProductTable.setLayout(new java.awt.BorderLayout());

        productName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Product ID", "Name", "Quantity", "Price" }
        ));
        jScrollPane1.setViewportView(productName);

        ProductTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(ProductTable, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Quantity");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buy");

        javax.swing.GroupLayout BuyPanelLayout = new javax.swing.GroupLayout(BuyPanel);
        BuyPanel.setLayout(BuyPanelLayout);
        BuyPanelLayout.setHorizontalGroup(
            BuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        BuyPanelLayout.setVerticalGroup(
            BuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuyPanelLayout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addGroup(BuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(BuyPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
     private void setupProductTable() {
    String[] columns = { "Product ID", "Name", "Quantity", "Price" };

    DefaultTableModel model = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // user cannot edit table
        }
    };

    productName.setModel(model);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        InventoryModel inventoryModel = new InventoryModel();
         SaleModel saleModel = new SaleModel();

java.awt.EventQueue.invokeLater(() -> new UserView(inventoryModel, saleModel).setVisible(true));
        
        /*java.awt.EventQueue.invokeLater(() -> new UserView().setVisible(true));*/
    }
    private void loadProductData() {
    DefaultTableModel model = (DefaultTableModel) productName.getModel();
    model.setRowCount(0); // clear table first

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[] {
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getPrice()
        });
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuyPanel;
    private javax.swing.JPanel ProductTable;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable productName;
    // End of variables declaration//GEN-END:variables
}
