/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.table.DefaultTableModel;
import Model.InventoryModel;
import Model.item;
import Model.SaleModel;
import javax.swing.JTable;
import Controller.UserController;
import java.awt.*;
import javax.swing.JOptionPane;



/**
 *
 * @author dell
 */
public class UserView extends javax.swing.JFrame {
    private InventoryModel inventoryModel;
    private SaleModel saleModel;
    private boolean lowStockAlertShown = false;
    private UserController userController;
    private String currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserView.class.getName());

    /**
     * Creates new form UserView
     */
    public UserView(InventoryModel inventoryModel , SaleModel saleModel,String username) {
       this.inventoryModel = inventoryModel;
       this.saleModel =  saleModel;
      this.currentUser = username;
       userController = new UserController(inventoryModel, saleModel, this);
        initComponents();
         //this.inventoryModel = inventoryModel;
         setupProductTable();
         loadProductData();
         lowStock();
         
         
         

          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProductTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productName = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sortCombo = new javax.swing.JComboBox<>();
        sortBtn = new javax.swing.JButton();
        BuyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User View");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("User Dashboard - Smart Inventory System");
        TitlePanel.add(jLabel1);

        getContentPane().add(TitlePanel, java.awt.BorderLayout.PAGE_START);

        ProductTable.setLayout(new java.awt.BorderLayout());

        productName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Product ID", "Name", "Quantity", "Price" }
        ));
        jScrollPane1.setViewportView(productName);

        ProductTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel5.setPreferredSize(new java.awt.Dimension(350, 10));
        jPanel1.add(jLabel5);

        jLabel4.setText("Sort By ");
        jPanel1.add(jLabel4);

        sortCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price (Ascending)", "Price (Descending)", "Quantity (Ascending)", "Quantity (Descending)", "Name (A-Z)", "Name (Z-A)" }));
        jPanel1.add(sortCombo);

        sortBtn.setText("Sort");
        jPanel1.add(sortBtn);

        ProductTable.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(ProductTable, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Product id");
        BuyPanel.add(jLabel2);

        jTextField2.setEditable(false);
        jTextField2.setColumns(15);
        BuyPanel.add(jTextField2);

        jLabel3.setText("Quantity");
        BuyPanel.add(jLabel3);

        jTextField1.setColumns(15);
        BuyPanel.add(jTextField1);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BuyPanel.add(jButton1);
        BuyPanel.add(jTabbedPane1);

        jButton3.setText("Purchase History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        BuyPanel.add(jButton3);

        getContentPane().add(BuyPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userController.buyProduct("user1");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //new PurchaseView(saleModel).setVisible(true);
        userController.openPurchaseHistory();
    }//GEN-LAST:event_jButton3ActionPerformed
     private void setupProductTable() {
    String[] columns = { "Product ID", "Name", "Quantity","Minimum", "Price" };

    DefaultTableModel model = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // user cannot edit table
        }
    };

    productName.setModel(model);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // InventoryModel inventoryModel = new InventoryModel();
       InventoryModel inventoryModel = new InventoryModel();
        inventoryModel.addItem(new item("P001", "Paracetamol",  3, 1, 20.00));

         SaleModel saleModel = new SaleModel();

/*java.awt.EventQueue.invokeLater(() -> new UserView(inventoryModel, saleModel).setVisible(true));*/

        UserView view = new UserView(inventoryModel,saleModel, "user1");
      view.setVisible(true);
      view.showLowStock();

        
        /*java.awt.EventQueue.invokeLater(() -> new UserView().setVisible(true));*/
    }
    public void loadProductData() {
    DefaultTableModel model = (DefaultTableModel) productName.getModel();
    model.setRowCount(0); 

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[] {
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
       
    }
}
    public void lowStock()
    {
       productName.setSelectionBackground(Color.PINK);
       productName.setSelectionForeground(Color.BLACK);
       productName.clearSelection();
       for (int row = 0; row<productName.getRowCount(); row++)
       {
           int quantity = Integer.parseInt(productName.getValueAt(row, 2).toString());
           int minimum = Integer.parseInt(productName.getValueAt(row, 3).toString());
           
           if (quantity<= minimum)
           {
               productName.addRowSelectionInterval(row , row);
           }
                  
           
       }
       
       
        
       
    }
    private void showLowStock()
    {
        if(lowStockAlertShown)
        {
            return ; // alerady shown 
        }
        boolean hasLowStock = false;
        for(item i: inventoryModel.getAllItems())
        {
            if(i.getQuantity()<=i.getMinimum())
            {
                hasLowStock = true;
                break;
            }
        }
        if(hasLowStock)
        {
            java.awt.Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Some products are running low on stock!",
                    "Low Stock alert",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                 );
            lowStockAlertShown = true;
            
        }
    }
    public JTable getInventoryTable()
    {
        return productName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuyPanel;
    private javax.swing.JPanel ProductTable;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable productName;
    private javax.swing.JButton sortBtn;
    private javax.swing.JComboBox<String> sortCombo;
    // End of variables declaration//GEN-END:variables
}
