/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.table.DefaultTableModel;
import Model.InventoryModel;
import Model.item;
import Model.SaleModel;
import javax.swing.JTable;
import Controller.UserController;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author dell
 */
public class UserView extends javax.swing.JFrame {
    private InventoryModel inventoryModel;
    private SaleModel saleModel;
    private boolean lowStockAlertShown = false;
    private UserController userController;
    private String currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserView.class.getName());

    /**
     * Creates new form UserView
     */
    public UserView(InventoryModel inventoryModel , SaleModel saleModel,String username) {
       this.inventoryModel = inventoryModel;
       this.saleModel =  saleModel;
      this.currentUser = username;
       userController = new UserController(inventoryModel, saleModel, this);
        initComponents();
         //this.inventoryModel = inventoryModel;
         setupProductTable();
         loadProductData();
         lowStock();
          javax.swing.SwingUtilities.invokeLater(() -> {
        showLowStock();
    });
         
         
         

          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProductTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productName = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchCombo = new javax.swing.JComboBox<>();
        searchbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sortCombo = new javax.swing.JComboBox<>();
        sortBtn = new javax.swing.JButton();
        BuyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User View");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("User Dashboard - Smart Inventory System");
        TitlePanel.add(jLabel1);

        getContentPane().add(TitlePanel, java.awt.BorderLayout.PAGE_START);

        ProductTable.setLayout(new java.awt.BorderLayout());

        productName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Product ID", "Name", "Quantity", "Price" }
        ));
        productName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productNameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productName);

        ProductTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        searchField.setColumns(10);
        jPanel1.add(searchField);

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linear", "Binary" }));
        jPanel1.add(searchCombo);

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchbtn);

        jLabel5.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jLabel5);

        jLabel4.setText("Sort By ");
        jPanel1.add(jLabel4);

        sortCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price (Ascending)", "Price (Descending)", "Quantity (Ascending)", "Quantity (Descending)", "Name (A-Z)", "Name (Z-A)" }));
        jPanel1.add(sortCombo);

        sortBtn.setText("Sort");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sortBtn);

        ProductTable.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(ProductTable, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Product id");
        BuyPanel.add(jLabel2);

        jTextField2.setEditable(false);
        jTextField2.setColumns(15);
        BuyPanel.add(jTextField2);

        jLabel3.setText("Quantity");
        BuyPanel.add(jLabel3);

        jTextField1.setColumns(15);
        BuyPanel.add(jTextField1);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BuyPanel.add(jButton1);
        BuyPanel.add(jTabbedPane1);

        jButton3.setText("Purchase History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        BuyPanel.add(jButton3);

        jLabel6.setPreferredSize(new java.awt.Dimension(250, 10));
        BuyPanel.add(jLabel6);

        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        BuyPanel.add(jButton2);

        getContentPane().add(BuyPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userController.buyProduct(currentUser);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //new PurchaseView(saleModel).setVisible(true);
        userController.openPurchaseHistory();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void productNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNameMouseClicked
        // TODO add your handling code here:
        int row = productName.getSelectedRow();
    if(row != -1) {
        String pid = productName.getValueAt(row, 0).toString();
        jTextField2.setText(pid);
    }  
    }//GEN-LAST:event_productNameMouseClicked

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
        userController.sortProducts();
    }//GEN-LAST:event_sortBtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        /*String method = searchCombo.getSelectedItem().toString(); // Linear / Binary
      
    if (method.equalsIgnoreCase("Linear")) {
        userController.searchProduct();   // your linear method
    } else {
        userController.binarySearchProduct(); //  binary
    }*/
      userController.searchProduct();   
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       userController.logout();
    }//GEN-LAST:event_jButton2ActionPerformed
     private void setupProductTable() {
    String[] columns = { "Product ID", "Name", "Quantity","Minimum", "Price" };

    DefaultTableModel model = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // user cannot edit table
        }
    };

    productName.setModel(model);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // InventoryModel inventoryModel = new InventoryModel();
       InventoryModel inventoryModel = new InventoryModel();
        inventoryModel.addItem(new item("P001", "Paracetamol",  3, 1, 20.00));
        inventoryModel.addItem(new item("P002", "Paracetamol",  1, 10, 50.00));
        inventoryModel.addItem(new item("P003", "Paracetamol",  2, 15, 30.00));

         SaleModel saleModel = new SaleModel();

/*java.awt.EventQueue.invokeLater(() -> new UserView(inventoryModel, saleModel).setVisible(true));*/

        UserView view = new UserView(inventoryModel,saleModel, "user1");
      view.setVisible(true);
      //view.showLowStock();

        
        /*java.awt.EventQueue.invokeLater(() -> new UserView().setVisible(true));*/
    }
    public void loadProductData() {
    DefaultTableModel model = (DefaultTableModel) productName.getModel();
    model.setRowCount(0); 

    for (item i : inventoryModel.getAllItems()) {
        model.addRow(new Object[] {
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
       
    }
}
    public void lowStock()
    {
       productName.setSelectionBackground(Color.PINK);
       productName.setSelectionForeground(Color.BLACK);
       productName.clearSelection();
       for (int row = 0; row<productName.getRowCount(); row++)
       {
           int quantity = Integer.parseInt(productName.getValueAt(row, 2).toString());
           int minimum = Integer.parseInt(productName.getValueAt(row, 3).toString());
           
           if (quantity<= minimum)
           {
               productName.addRowSelectionInterval(row , row);
           }
                  
           
       }
       
       
        
       
    }
    private void showLowStock()
    {
        if(lowStockAlertShown)
        {
            return ; // alerady shown 
        }
        boolean hasLowStock = false;
        for(item i: inventoryModel.getAllItems())
        {
            if(i.getQuantity()<=i.getMinimum())
            {
                hasLowStock = true;
                break;
            }
        }
        if(hasLowStock)
        {
            java.awt.Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Some products are running low on stock!",
                    "Low Stock alert",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                 );
            lowStockAlertShown = true;
            
        }
    }
    public String getSearchText() {
    return searchField.getText();
}


public String getSearchType() {
    return searchCombo.getSelectedItem().toString();
}


    public JTable getInventoryTable()
    {
        return productName;
    }
    public String getSelectedSortOption() {
    return sortCombo.getSelectedItem().toString();
}
    // merge sort
    public  ArrayList<item> mergeSortByPriceAscending(ArrayList<item> list) {

    if (list.size() <= 1) {
        return list;
    }

    int mid = list.size() / 2;

    ArrayList<item> left = new java.util.ArrayList<>(list.subList(0, mid));
    ArrayList<item> right = new java.util.ArrayList<>(list.subList(mid, list.size()));

    left = mergeSortByPriceAscending(left);
    right = mergeSortByPriceAscending(right);

    return mergeByPriceAscending(left, right);
}

public ArrayList<item> mergeByPriceAscending(ArrayList<item> left,
                                                        ArrayList<item> right) {

    ArrayList<item> result = new ArrayList<>();

    while (!left.isEmpty() && !right.isEmpty()) {

        double leftPrice = left.get(0).getPrice();
        double rightPrice = right.get(0).getPrice();

        // ASCENDING
        if (leftPrice <= rightPrice) {
            result.add(left.remove(0));
        } else {
            result.add(right.remove(0));
        }
    }

    result.addAll(left);
    result.addAll(right);

    return result;
}
// merge sort by descending price
public ArrayList<item> mergeSortByPriceDescending(ArrayList<item> list) {

    if (list.size() <= 1) {
        return list;
    }

    int mid = list.size() / 2;

    ArrayList<item> left = new ArrayList<>(list.subList(0, mid));
    ArrayList<item> right = new ArrayList<>(list.subList(mid, list.size()));

    left = mergeSortByPriceDescending(left);
    right = mergeSortByPriceDescending(right);

    return mergeByPriceDescending(left, right);
}

public ArrayList<item> mergeByPriceDescending(ArrayList<item> left,
                                                         ArrayList<item> right) {

    ArrayList<item> result = new java.util.ArrayList<>();

    while (!left.isEmpty() && !right.isEmpty()) {

        double leftPrice = left.get(0).getPrice();
        double rightPrice = right.get(0).getPrice();

        //  DESCENDING
        if (leftPrice >= rightPrice) {
            result.add(left.remove(0));
        } else {
            result.add(right.remove(0));
        }
    }

    result.addAll(left);
    result.addAll(right);

    return result;
}
// asscending  insertion by quantity
public void insertionSortByQuantityAscending(java.util.ArrayList<item> list) {

    int size = list.size();

    for (int step = 1; step < size; step++) {

        item key = list.get(step);
        int keyQty = key.getQuantity();
        int j = step - 1;

        while (j >= 0 && keyQty < list.get(j).getQuantity()) {
            list.set(j + 1, list.get(j));
            j--;
        }

        list.set(j + 1, key);
    }
}

// insertion quantity for descending
public static void insertionSortByQuantityDescending(java.util.ArrayList<item> list) {

    int size = list.size();

    for (int step = 1; step < size; step++) {

        item key = list.get(step);
        int keyQty = key.getQuantity();
        int j = step - 1;

       // DESCENDING: bigger quantity first
        while (j >= 0 && keyQty > list.get(j).getQuantity()) {
            list.set(j + 1, list.get(j));
            j--;
        }

        list.set(j + 1, key);
    }
}



public void loadSortedProductData(ArrayList<item> sortedList) {

    DefaultTableModel model = (DefaultTableModel) productName.getModel();
    model.setRowCount(0); // clear table

    for (item i : sortedList) {
        model.addRow(new Object[]{
            i.getProductId(),
            i.getName(),
            i.getQuantity(),
            i.getMinimum(),
            i.getPrice()
        });
    }
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuyPanel;
    private javax.swing.JPanel ProductTable;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable productName;
    private javax.swing.JComboBox<String> searchCombo;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton sortBtn;
    private javax.swing.JComboBox<String> sortCombo;
    // End of variables declaration//GEN-END:variables
}
